/**
 * TAGS + TAG_MAP por defecto (fallback si Firebase está vacío).
 * Sincroniza a RT con el panel o firebaseTagMapRealtime.seedTagMapFromObject.
 */

export const TAGS = [
  "Sostenibilidad", "Gestión del Agua", "Gobernanza y Políticas Públicas", "Responsabilidad Familiar Corporativa",
  "Familia y Paternidad", "Fortalecimiento Institucional", "Confianza Institucional", "Educación",
  "Formación del Carácter", "Liderazgo Educativo", "Políticas Públicas", "Desarrollo Sostenible",
  "Ciudadanía", "Bienestar Social", "Gobernanza", "Responsabilidad Social", "Agroindustria",
  "Tecnologías para la Industria Alimentaria", "Biotecnología", "Desarrollo Social",
  "Jóvenes y Vida Espiritual", "Jóvenes y Trabajo", "Jóvenes y Matrimonio y Familia", "Relaciones Interpersonales",
];

export const TAG_MAP_DEFAULT = {
  "CONAGUA": [1, 0, 14], "IMTA": [1, 0], "Sec. Gestión Integral del Agua de Jalisco": [1, 14], "UNESCO Water Programme": [1, 0, 14], "Global Water Partnership": [1, 0, 14], "SIAPA": [1], "Comisión Estatal del Agua": [1], "Consejo Consultivo del Agua": [1, 14, 2],
  "Secretaría de Educación de Jalisco": [7, 8, 10], "Secretaría de Salud de Jalisco": [13, 19], "Sec. Medio Ambiente (SEMADET)": [0, 11], "Secretaría de Desarrollo Económico": [15, 16], "Secretaría del Trabajo de Jalisco": [3, 21], "Secretaría General de Gobierno": [2, 14, 6], "Secretaría de Planeación y Participación": [2, 10, 12], "Secretaría de Cultura de Jalisco": [7, 12], "Sec. Desarrollo Energético Sustentable": [0, 11], "Sec. Sistema de Asistencia Social": [13, 19], "Municipio de Zapopan": [12, 14, 11], "Congreso del Estado de Jalisco": [2, 10], "IIEG Jalisco": [2, 10], "COECYTJAL": [18, 0], "SEDECO Jalisco": [15, 16], "Sec. Técnica del Consejo de Participación": [2, 12],
  "COPARMEX Jalisco": [3, 15], "CCIJ": [16, 15], "CMIC": [11, 14], "CANACO Guadalajara": [15, 16], "COMCE": [15], "CIAJ": [16, 17], "IMEF": [15, 5], "Fundación IMEF": [15, 5], "CCPG": [5, 10], "Fundación Expo GDL": [15, 12], "CEMEFI": [15, 19], "Redwood Ventures": [15], "APICE": [7, 8], "AFEET": [15], "FIMPES": [7, 5], "ARSEE": [7], "MetaRed ESG": [0, 11], "Consejo Regulador del Tequila": [16, 17],
  "Intel": [17, 7], "Hewlett Packard Enterprise": [17], "Oracle": [17], "Bosch": [0, 17], "Continental": [17], "Flex": [17], "Sanmina": [17], "Foxconn": [17], "TCS": [3, 17], "Jabil": [17], "Sigma Alimentos": [16, 17], "SuKarne": [16], "PISA Farmacéutica": [13, 18], "Corporativo Fragua": [13, 19], "Megacable": [17, 12], "GAP": [11],
  "CANIETI (Alta Tecnología)": [17], "CLAUTJAL (Automotriz)": [17], "Clúster Agroalimentario": [16, 17], "Clúster Ing. Biomédica": [18, 13], "Clúster Innovación y Diseño": [17], "Clúster Médico de Jalisco": [13, 18],
  "U de G": [7, 0], "UDLAP": [7, 8], "ITESO": [7, 19], "Tec de Monterrey": [7, 17], "IAE Business School": [3, 4], "UNIVA": [7], "UAG": [7], "Universidad de California en Irvine": [1, 0],
  "Jubilee Centre (U. Birmingham)": [8, 9], "Pontificia U. Santa Cruz (Roma)": [20, 22, 23], "American Accounting Association": [5],
  "Liceo del Valle": [7, 8], "Altamira": [7, 8], "La Cima": [7, 8], "Los Altos": [7, 8], "Torreblanca": [7, 8], "Palmares": [7, 8],
  "Colonos de Ciudad Granja": [12, 11], "Asociación Vecinal": [12, 14], "Jalisco S.O.S.": [14, 12], "Parroquia local": [20, 13], "Escuelas de la comunidad": [7, 8], "Instituto Jalisciense de la Vivienda": [11, 14], "Consejo Ciudadano de Seguridad": [14, 12], "Comité Beatificación Fray Antonio Alcalde": [20],
  "El Informador": [2, 12], "Canal 44": [2, 12], "Premio Jalisco de Periodismo": [2], "Cámara Nal. de la Industria Cinematográfica": [15],
  "Departamento de Estado de EE.UU.": [2, 14], "Consulado de España": [2], "Embajada de Italia": [2],
  "CONAHCyT": [18, 0], "Fondos UP Investigación": [7], "Fondos internacionales": [0],
  "Gestión del agua urbana": [1, 0], "Educación del carácter": [7, 8], "Responsabilidad familiar corporativa": [3, 4], "Sostenibilidad alimentaria": [16, 17], "Juventud y valores": [20, 21], "Desarrollo comunitario": [11, 12, 19],
  "Agua y gestión hídrica": [1, 0], "Ciudades inteligentes y sostenibles": [0, 11, 17], "Construcción sostenible": [0, 11],
  "Eficiencia energética y renovables": [0, 11], "Educación del carácter y virtudes": [8, 7],
  "Liderazgo-servicio educativo": [9, 7], "Evaluación y calidad educativa": [7, 5],
  "Filosofía de la educación": [7, 8], "Familia y armonización trabajo-familia": [3, 4],
  "Paternidad y maternidad": [4, 13], "Derechos humanos y dignidad": [2, 10],
  "Derecho internacional y comparado": [2], "Pueblos indígenas y diversidad cultural": [12, 2],
  "Inteligencia artificial y machine learning": [17, 18], "Ciencia de datos y análisis": [17],
  "Ciberseguridad y blockchain": [17], "Robótica y dispositivos médicos": [17, 13],
  "IoT y sistemas embebidos": [17, 0], "Nanotecnología alimentaria": [16, 18],
  "Inocuidad y seguridad alimentaria": [16, 17], "Biotecnología y escalamiento productivo": [18, 16],
  "Salud mental y neurociencias": [13, 19], "Psicología positiva y neurodesarrollo": [13, 8],
  "Comunicación corporativa y reputación": [15, 5], "Periodismo y medios digitales": [12],
  "Ética profesional y de la IA": [5, 15], "Compliance e integridad empresarial": [5, 6],
  "Políticas públicas y gobernanza": [2, 10, 14], "Desarrollo regional y economía aplicada": [15, 11],
  "Emprendimiento y negocios": [15], "Logística y cadena de suministro": [15, 16],
  "Realidad virtual y aumentada": [17], "Videojuegos y gamificación": [17, 7],
  "Ingeniería sísmica y estructural": [11], "Diseño arquitectónico e IA": [17, 11],
  "Electrónica de potencia": [17], "Ingeniería de materiales y polímeros": [18, 17],
  "Holografía y procesamiento de imágenes": [17], "Comunicaciones inalámbricas": [17],
  "Identidad cultural y patrimonio": [12, 7], "Teología y liturgia": [20],
  "Economía de la educación": [7, 15],
  "C. Hidroadaptativas": [1, 0, 2, 14], "Centro de Investigación": [1, 0, 2],
  "CONFyE": [3, 4, 5, 6], "Centro FARO": [3, 4, 5],
  "EDUCARACTER": [7, 8, 9, 10], "Educaracter": [7, 8, 9, 10],
  "Comunidad Panamericana": [11, 12, 13, 14, 15, 19], "Comunidad UP": [11, 12, 13, 14, 15],
  "Sostenibilidad Alimentaria": [16, 17, 18, 19], "Alive UP": [16, 17, 18],
  "FOOTPRINTS": [20, 21, 22, 23], "Footprints": [20, 21, 22, 23],
  "Centro de Investigación de Ciudades Hidroadaptativas": [1, 0, 2, 14],
  "CONFyE (Centro FARO)": [3, 4, 5, 6],
  "Sostenibilidad Alimentaria (Alive UP)": [16, 17, 18, 19],
};
